services:
  - type: web
    name: courier-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: courier-backend
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: courier-db
          property: connectionString

databases:
  - name: courier-db
    databaseName: courier_db
    user: courier
    plan: free
